version: '3'

services:
  dev:
    build: .
    container_name: tonoperfecto
    env_file: .env
    command: npm run startdev
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
